### ISSUE TITLE
PerkinElmer/Varex XRD 3025

### ISSUE THREAD

**Issue by AlexanderWirner** [esrf-bliss/Lima-camera-perkinelmer#6]
Dear all, 
Does anyone have experience with the XRD 3025 and LImA?

**Comment by laurent-claustre** [comment]
Dear Alexander,
at ESRF we have XRD 1611 (CP3) and XRD 1621 (CN3-ES). We did reinstall the XRD 1611 detector on a windows10 computer with the newer XIS SDK software version  33.7.206. A conda package (perkinelmer-sdk 33.7.206) will be automatically installed if you install  the lima camera conda package (lima-camera-perkinelmer(-tango) 1.10.0).
Hope this can help.

**Comment by AlexanderWirner** [comment]
Dear Laurent, 
thank you for your quick response. 
Cause I´m quite new to the business it took me some time, but I could manage to install and run the lima simulator as a first test and afterwards I also could successful install the perkin-elmer-tango package via Mamba 
`mamba create -n perkinelmertango -c conda-forge -c esrf-bcu lima-camera-perkinelmer-tango`
but got an error that there is no camera when using your python code example (https://lima1.readthedocs.io/en/latest/camera/perkinelmer/doc/index.html#how-to-use). 

> (perkinelmertango) D:\anaconda\envs\perkinelmertango>python test_perkinelmertango.py
> DLLMain()-DLL_PROCESS_ATTACH
> Init Mutex created
> Read Mutex created
> [2023/01/16 12:15:56.515539] 0000027169782B90     *Camera*lima::PerkinElmer::Interface::_InitDetector (C:\Miniconda3\conda-bld\lima-camera-perkinelmer_1639060342149\work\src\PerkinElmerInterface.cpp:116)-Error: Exception(Error):  [thrown]
> Traceback (most recent call last):
>   File "test_perkinelmertango.py", line 6, in <module>
>     hwint = PerkinElmer.Interface()
> limacore.Exception: Hardware: lima::PerkinElmer::Interface::_InitDetector(C:\Miniconda3\conda-bld\lima-camera-perkinelmer_1639060342149\work\src\PerkinElmerInterface.cpp, 116): Error: No camera found
> Close Init Mutex
> Close Read Mutex

With the XIS Software I could find the detector.
Is there any configuration I missed for lima?

**Comment by laurent-claustre** [comment]
Hi we have the same issue as you with the XRD 1621 models (we have two), I should work in this issue in the coming weeks. Could be an issue with sdk version we link on to the Lima code, SDK version 33.7.206 . I  will certainly contact the support team to get a new sdk for those models.

**Comment by AlexanderWirner** [comment]
Oh yes, that is an interesting point. We are using an old version from February 2021 (33.6.2871) in XIS. 

But I probably can't just replace the xisl.dll, xisl.lib and acq.h from the lima environment folders with those from the old version, can I?

**Comment by laurent-claustre** [comment]
Hi Alex,
we fixed the issue with the detector model XRD 1621. That was just installation issue, the Redistruables for VisualStudio 2013 was not installed. There is a vcredist_x64.exe installer under XISL\Redistruables Visual Studio 2013\.
If you want I can forward you the email I did received from Varex support team.
